name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  buildapp:
    name: build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: list folders
        run: echo "PWD:" && pwd && echo "WORKSPACE:" && echo ${{ github.workspace }}
      - name: list all files
        run: ls -la
      - name: read docker properties
        uses: madhead/read-java-properties@latest
        id: docker
        with:
          file: docker.properties
          all: true
      - name: dockerhub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            geekymon2/${{ steps.docker.outputs.IMAGE_NAME }}:${{ steps.docker.outputs.MAJOR_VERSION }}.${{ steps.docker.outputs.MINOR_VERSION }}.${{ github.run_number }}
            geekymon2/${{ steps.docker.outputs.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ARTIFACT_NAME=${{ steps.docker.outputs.ARTIFACT_NAME }}
            IMAGE_VERSION=${{ steps.docker.outputs.IMAGE_NAME }}:${{ steps.docker.outputs.MAJOR_VERSION }}.${{ steps.docker.outputs.MINOR_VERSION }}.${{ github.run_number }}
